---
when:
  event: push
  branch: feature/hadolint

steps:
############# HADOLINT #############
- name: hadolint
  image: hadolint/hadolint:latest
  entrypoint: ["hadolint", "--failure-threshold", "error", "--warning", "DL4000", "--warning", "DL3020", "Dockerfile"]

############## PRETTIER ##############
- name: prettier
  image: woodpeckerci/plugin-prettier:next
  settings:
    check: false

############## PRETTIER-DIFF ##############
- name: show-prettier-diff
  image: alpine/git
  commands:
    - git diff --stat
    - git diff --color -U1
